backend:
  name: auth0
  branch: main
  auth0:
    domain: dev-uwnuy0iejoajr7q1.us.auth0.com
    client_id: 3NNKwQOTILQsdjeHksJv5sTKYoc12gZL

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "category"
    label: "Categories"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "PDF Link", name: "pdf", widget: "string" }
      - { label: "Video Link", name: "video", widget: "string" }
