backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["Math", "Science", "English", "Hindi", "S.St"] }
      - { name: "link", label: "Video or PDF Link", widget: "string" }
